[workspace]
resolver = "2"
members = [
    "crates/kotor-ncs-isa",
    "crates/kotor-formats",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
license = "MIT"
repository = "https://github.com/arrenkaetris/kotor-formats"

[workspace.dependencies]
kotor-ncs-isa = { version = "0.1.0", path = "crates/kotor-ncs-isa" }

[profile.release]
opt-level = 2
lto = "thin"
strip = true
